service:
  name: serverless-api-typescript

plugins:
  - serverless-webpack
  - serverless-cloudformation-resource-counter
  - serverless-plugin-iam-checker
  - serverless-plugin-test-helper
  - serverless-prune-plugin
  - serverless-lumigo

provider:
  name: aws
  stage: ${self:custom.stage}
  runtime: nodejs12.x
  apiGateway:
    # Enable gzip compression for responses > 1 KB
    minimumCompressionSize: 1024
  environment:
    NODE_ENV: PRODUCTION
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1 # https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html
    LAMBDA_WRAPPER_LOG: true
    MESSAGES_TABLE: !Ref MessagesTable
    INVALIDATE_CACHE_TOPIC: !Ref InvalidateCacheTopic
  iamRoleStatements:
    - Effect: Allow
      Action: cloudfront:CreateInvalidation
      Resource: '*'
    - Effect: Allow
      Action: sns:Publish
      Resource: !Ref InvalidateCacheTopic
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:GetItem
      Resource: !GetAtt [MessagesTable, Arn]

custom:
  stage: ${opt:stage, env:STAGE, 'local'}
  invalidateCacheTopic: ${self:service.name}-${opt:stage, self:provider.stage}-invalidate-cache
  # Serverless plugin configurations
  # https://github.com/manwaring/serverless-plugin-iam-checker
  iamChecker:
    resources:
      allowWildcardOnly: true # Unfortunately need to allow wildcard only because CloudFront doesn't support resource ARNs in IAM
  # https://github.com/lumigo-io/serverless-lumigo-plugin
  lumigo:
    token: ${env:LUMIGO_TOKEN}
    nodePackageManager: npm
  # https://github.com/claygregory/serverless-prune-plugin
  prune:
    automatic: true
    number: 3
  # https://github.com/drexler/serverless-cloudformation-resource-counter
  warningThreshold: 100
  # https://github.com/serverless-heaven/serverless-webpack
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk

  package:
    exclude:
      - .git
      - .env
      - package-lock.json
      - package.json
      - README.md
    excludeDevDependencies: true

functions:
  load-sample-data:
    handler: app/messages/sample-data/load.handler

  get-all-messages:
    handler: app/messages/get-all.handler
    events:
      - http:
          method: get
          path: messages

  get-message:
    handler: app/messages/get.handler
    events:
      - http:
          method: get
          path: messages/{id}
          request:
            parameters:
              paths:
                id: true

  add-message:
    handler: app/messages/add.handler
    events:
      - http:
          method: post
          path: messages

  delete-message:
    handler: app/messages/delete.handler
    events:
      - http:
          method: delete
          path: messages/{id}
          request:
            parameters:
              paths:
                id: true

  update-message:
    handler: app/messages/update.handler
    events:
      - http:
          method: put
          path: messages/{id}
          request:
            parameters:
              paths:
                id: true

  invalidate-cache:
    handler: app/cache/invalidate.handler
    events:
      - stream:
          type: dynamodb
          arn: !GetAtt MessagesTable.StreamArn
      - sns:
          arn: !Ref InvalidateCacheTopic
          topicName: ${self:custom.invalidateCacheTopic}
    environment:
      API_CLOUDFRONT: !Ref APICloudFrontDistribution

resources:
  Description: Serverless API starter for the ${opt:stage, self:provider.stage} stage using Serverless Framework and TypeScript

  Resources:
    InvalidateCacheTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.invalidateCacheTopic}

    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    APICloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: Powering the ${opt:stage, self:provider.stage} Pariveda Serverless Starter
          CustomErrorResponses:
            - ErrorCachingMinTTL: 0
              ErrorCode: 503
          DefaultCacheBehavior:
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - PATCH
              - POST
              - DELETE
            TargetOriginId: APIGateway
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 2592000
            ForwardedValues:
              QueryString: true
          Enabled: true
          Origins:
            - Id: APIGateway
              DomainName:
                Fn::Join:
                  - '.'
                  - - !Ref ApiGatewayRestApi
                    - execute-api
                    - !Ref AWS::Region
                    - amazonaws.com
              OriginPath: /${opt:stage, self:provider.stage}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

    ApiDocumentationBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    ApiDocumentationBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ApiDocumentationBucket
        PolicyDocument:
          Id: APIDocumentationBucketReadPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: !Join
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref ApiDocumentationBucket
                  - /*

  Outputs:
    ApiDocumentationBucket:
      Value: !Ref ApiDocumentationBucket
      Description: Bucket for hosting Api documentation

    ApiDocumentationUrl:
      Value: !GetAtt [ApiDocumentationBucket, WebsiteURL]
      Description: URL for Api documentation website

    CloudFrontEndpoint:
      Description: URL of the CloudFront endpoint
      Value:
        Fn::Join:
          - ''
          - - https://
            - !GetAtt [APICloudFrontDistribution, DomainName]
